version: "2.1"

services:
 back:
  container_name: pfemback
  image: pfem-back
  ports:
   - "3035:3035"
  networks:
   - back-db
  depends_on:
   - db
    
 db:
  container_name: pfemdb
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=pfemanager
  networks:
    - back-db
  volumes:
   - mysql-data:/var/lib/mysql
   - ./initsql:/docker-entrypoint-initdb.d
  ports:
    - "3307:3306"
  expose:
    - "3307"
            
                
 front:
  container_name: pfemfront
  image: pfem-front
  ports:
   - "4200:80"
  expose:
    - "4200"
            
networks:
 back-db:
 
volumes:
 mysql-data:
