version: "2.1"

services:
 back:
  container_name: pfem-back
  image: pfem-back
  ports:
   - "3035:3035"
  networks:
   - back-db
  depends_on:
   - db
    
 db:
  container_name: pfem-db
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=pfemanager
  networks:
    - back-db
  volumes:
   - mysql-data:/var/lib/mysql
   - ./initsql:/docker-entrypoint-initdb.d
  ports:
    - "3307:3306"
  expose:
    - "3307"
  healthcheck:
   test: "/usr/bin/mysql --user=root --password=root --execute \"USE pfemanager;\"" # login to mysql and check db existance
   timeout: 20s
   retries: 10
            
                
#  frontend:
#   container_name: pfem-front
#   image: pfem-front
#   ports:
#    - "4200:80"
            
networks:
 back-db:
 
volumes:
 mysql-data:
